target="template_release"
debug_symbols="no"
optimize="size"
lto="full"

deprecated="no"
vulkan="no"
use_volk="no"
openxr="no"
minizip="no"

modules_enabled_by_default="no"
module_gdscript_enabled="yes"
module_text_server_adv_enabled="yes"
module_freetype_enabled="yes"
module_msdfgen_enabled="yes"
module_godot_physics_2d_enabled="yes"
module_svg_enabled="yes"
module_webp_enabled="yes"
module_jpg_enabled="yes"